### ISSUE TITLE
SecurityProfiles and extendedGuarantee attributes

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#133]
SecurityProfiles are intended as a shortcut and alignment regarding the certification profiles. However, the result is a logical inconsistency if e.g. [idsc:BASE_CONNECTOR_SECURITY_PROFILE ids:securityGuarantee idsc:AUDIT_LOCAL_LOGGING](https://github.com/IndustrialDataSpace/InformationModel/blob/060bea2ce97c721719fe6029e414770c074d5dfc/codes/SecurityGuarantee.ttl#L207) but a connector specifies also:
<>  ids:extendedGuarantee  idsc:AUDIT_REMOTE_TRACING .

Now `ids:securityGuarantee idsc:AUDIT_LOCAL_LOGGING` should be beaten by `ids:extendedGuarantee  idsc:AUDIT_REMOTE_TRACING`. That's not how RDF works.

Option 1: Remove the SecurityProfiles completely and stay with the more detailed ids:SecurityGuarantee. Con: Increases the size of the DAT.

Option 2: ??

**Comment by Madmatti** [comment]
Option 2: Reformulate the individual guarantees to be strictly incremental, so that if a higher value is chosen, the lower value still holds true.
E.G. instead of ids:LocalDataConfidentialityGuarantee with three options (1) NONE, (2) SECURE_ERASURE (3) FULL_ENCRYPTION, we split this into two
ids:LocalDataErasureGuarantee (1) NONE, (2) SECURE_ERASURE
ids:LocalDataEncryptionGuarantee (1) NONE, (2) FULL_ENCRYPTION

This would mean that "NONE" doesn't mean "I definitely won't do anything" but "I promise to at least do: nothing", which trivially holds true.

**Comment by HaydarAk** [comment]
@sebbader Could you give us a update regarding this issue?
We did some changes on the security-related modeling. 

Issue still present?

**Comment by JohannesLipp** [comment]
Closed due to inactivity. Please comment & re-open if required.
