### ISSUE TITLE
Shapes NS does not resolve

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#142]
Currently, the shapes [namespace ](https://github.com/IndustrialDataSpace/InformationModel/blob/72b658b01881ad4ba3a567fd68019eabeb7fbd8b/testing/content/ResourceShape.ttl#L10) does not resolve properly.

Changing it from https://github.com/IndustrialDataSpace/InformationModel/testing/ to https://github.com/IndustrialDataSpace/InformationModel/tree/master/testing or creating proper redirects (@prefix test: <https://w3id.org/idsa/test>, similar to https://w3id.org/idsa/core) might be better.

**Comment by HaydarAk** [comment]
Fixed that in recent updates. 

I still like the idea of the https://w3id.org/idsa/test prefix for shapes.

**Comment by HaydarAk** [comment]
Fixed in a recent commit. 
All `shapes:` now point to: `https://github.com/International-Data-Spaces-Association/InformationModel/tree/master/testing/`
We can also use:
- `https://w3id.org/idsa/shacl/` with the directory structure of the `testing` subdirectory as an URL path to directly reference a shacl shape. 
E.g.:
`https://w3id.org/idsa/shacl/content/ResourceShape` resolves to
`https://raw.githubusercontent.com/International-Data-Spaces-Association/InformationModel/develop/testing/content/ResourceShape.ttl`

- `http://w3id.org/idsa/shacl` without any path to receive all shacl shapes as a single zipped file.
