### ISSUE TITLE
Allow multiple targetArtifacts for Contracts

### ISSUE THREAD

**Issue by jpieperbeck** [International-Data-Spaces-Association/InformationModel#257]
Currently, only one targetArtifact can be assigned to a Contract (Offer, Agreement, ...). 
Proposal: Allow multiple targetArtifacts (as list, collection, o.e.). This should be handled as if the associated contract is generated for each individual artifact. 

This would allow for much shorter contracts if multiple artifacts are treated with the same set of policies while keeping the artifacts themself separated.

Example:
```
{
  "targetArtifact": [artifact_1, artifact_2],
  "permission":foo
}
```
should be handled the same as using
```
{
  "targetArtifact":artifact1,
  "permission":foo
}
```
and 
```
{
  "targetArtifact":artifact2,
  "permission":foo
}
```

**Comment by sebbader** [comment]
I would like to promote the ODRL "xxx-Collection" construct. That would appear something like:

```
[ {
   "targetArtifact": {
       "@type": "ids:ArtifactCollection",
       "@id": "http://this-asset-collection"
   },
   "permission": foo
},
{
   "@type": "ids:Artifact",
   "@id": "artifact1",
   "ids:partOf": "http://this-asset-collection"
},
{
   "@type": "ids:Artifact",
   "@id": "artifact2",
   "ids:partOf": "http://this-asset-collection"
} ]
```

**Comment by sebbader** [comment]
Problem: The members of the asset collection are not (yet/necessarily) in the JSON-LD Contract itself. That implies that the exchangeable JSON-LD is not self-contained, which might be an issue for its governance. For instance, I can change the collection after we agreed on a contract...

**Comment by jpieperbeck** [comment]
Is there an issue with treating it as a generic list? This to me would feel like the easiest and most intuitive solution, especially since this is the way that multiple constrains/permissions/dutys for the same artifact are handled.

**Comment by sebbader** [comment]
I think there are two answers:
A) I am pretty sure your approach is correct, I just want to see @HaydarAk's opinion.
B) I always wanted to use the Collections, and your need seems to be a good opportunity for that :-)

**Comment by HaydarAk** [comment]
>Currently, only one targetArtifact can be assigned to a Contract (Offer, Agreement, ...).

From an Information Model perspective, this is not correct I think. See last section of my answer for a detailed explanation.

>A) I am pretty sure your approach is correct, I just want to see @HaydarAk's opinion.
B) I always wanted to use the Collections, and your request seems to be a good opportunity for that :-)

Yes. As described below, the approach is correct and requries no changes in the Information Model. 
Using asset collections would allow us: 
- to wrap multiple artifacts together. -> A cleaner reference, since we can reference the whole set of artifacts instead of the single artifacts.
- define constraint refinements on the assets inside a collection.

[Check the corresponding ODRL documentation for asset collections.](https://www.w3.org/TR/odrl-model/#constraint-asset). I do not have any objection to add asset collections for a future release. 

For the sake of completeness, I explain the relation between contracts, permissions and artifacts a bit more in detail. 

---

A **Contract** (superclass of Offer / Agreement / Request) can have **Permissions**. https://github.com/International-Data-Spaces-Association/InformationModel/blob/b113503b00c313a1040b6cc9617db7d30be5dd10/model/contract/Contract.ttl#L111-L116

**Rule** (superclass of Permission) holds the reference to the target artifacts .
https://github.com/International-Data-Spaces-Association/InformationModel/blob/b113503b00c313a1040b6cc9617db7d30be5dd10/model/contract/Rule.ttl#L104-L110

We do not restrict the users to only refer to one artifact, with `targetArtifact`. https://github.com/International-Data-Spaces-Association/InformationModel/blob/b113503b00c313a1040b6cc9617db7d30be5dd10/testing/contract/RuleShape.ttl#L71-L77

---

Therefore, you already should be able to do the following using json arrays. 
```
{
"@type" : "ids:Contract",
    ...
   "permission": {
     ...
       "targetArtifact": [{
       "@type": "ids:Artifact",
       "@id": "id1"
       },
       {
       "@type": "ids:Artifact",
       "@id": "id2"
       }],                 
}
}
```

**Comment by sebbader** [comment]
RDF-wise you are certainly correct, @HaydarAk, however, our tools currently expect only one object. `idsm:OneToMany` is not set...

However, my main obligation is the introduced complexity when promoting Collections. Please take a look at the ContentTemplate I am currently working on: https://github.com/International-Data-Spaces-Association/InformationModel/blob/3064b26bfbf9e894ef39a0241a525204bf38846f/codes/templates/ArtifactTemplates/ARTIFACT_TEMPLATE.ttl#L26
The intention is to have all building blocks explicitly outlined. I am using a strange mix of RDF and RegEx, I know it's not easy to read. No better alternative in sight though... What I want to say: It sounds simple but the additional effort on the consuming side is really significant. We must not underestimate this.

**Comment by riannella** [comment]
You can certainly use an odrl:AssetCollection to represent a collection of assets that the policy applies to. 
You can then use odrl:partOf to indicate which individual target assets are part of the AssetCollection

**Comment by JohannesLipp** [comment]
@hosseinzadeha Can you re-evaluate if this is still relevant? Any maybe comment with your expertise in the ODRL context? Thank you!

**Comment by riannella** [comment]
Just to clarify, you can have many individual assets in a Policy - see Example 26 here: https://www.w3.org/TR/odrl-model/#composition
This is the 'compact' version of the Policy, which _would/could_ be expanded to the 'atomic' policy (see Example 27).

Alternatively, if the assets are part of an identifiable collection, then the "Asset Collection" can be used: https://www.w3.org/TR/odrl-model/#constraint-asset

**Comment by hosseinzadeha** [comment]
Thank you @riannella. I think your explanation helped to clarify how to connect a policy to a collection of Assets. Though it is still unclear for us how to refer to an Artifact which hasn't been materialized yet. For it I created a new issue:
https://github.com/International-Data-Spaces-Association/InformationModel/issues/557

@JohannesLipp In my opinion, we can close this one.
