### ISSUE TITLE
Add ids:Artifact as a subclass of ids:Asset.

### ISSUE THREAD

**Issue by changqin26** [International-Data-Spaces-Association/InformationModel#512]
here, target points to Artifact, whereas the infomodel follows ODRL's understanding "Rule -target-> Asset", and ids:Resource is a subclass of ids:Asset, but ids:Artifact is not.

**Comment by changqin26** [comment]
Hi @clange here is a reminder. You may need to investigate this issue. Thank you!

**Comment by lcomet** [comment]
Hi @clange @changqin26 @JohannesLipp I was tracking the error related to this issue. Here is what I found:

It seems the problem originated in the serialization process, even before we run Widoco because we have different content in the serialization folder than there is in the definition of `ids:Artifact` as we have in _Artifact.ttl_ in the model.

In fact, in the **main** and **develop**  branches we have the following definition in _docs/serialization/ontology.ttl_:

`ids:Artifact rdfs:subClassOf ids:RepresentationInstance`

However, in the same branches, in _model/content/Artifact.ttl_ we have:
`ids:Artifact rdfs:subClassOf ids:Asset, ids:RepresentationInstance;` and 
`ids:Artifact rdfs:subClassOf odrl:Asset, ids:RepresentationInstance, ids:Described ;` respectively

I additionally include here the info on how we are generating the documentation with Widoco:

We generate the documentation and serializations (for each released version) from the `https://github.com/International-Data-Spaces-Association/InformationModel/releases/tag/`
_"_correspondingReleaseVersion_Source code.zip"_

For example for _v4.1.0: InformationModel-4.1.0/docs/serializations/ontology.ttl_ where we have the following triple:

`ids:Artifact rdfs:subClassOf ids:RepresentationInstance .`

However, in _InformationModel-4.1.0/model/content/Artifact.ttl_ we have the following triple: 
`ids:Artifact rdfs:subClassOf ids:Asset, ids:RepresentationInstance .`

**Comment by JohannesLipp** [comment]
@lcomet thank you for this investigation! Seems like we either forgot to re-generate the serializations for some versions, or we did not merge these into the respective branches (i.e., main or develop maybe?). There is some `doc` directory on main+develop, but it seems to be inconsistent indeed. What do you suggest?

**Comment by lcomet** [comment]
@JohannesLipp I am working on modifying the serialization process and testing the changes. 
I will keep you updated.

**Comment by JohannesLipp** [comment]
Thank you very much @lcomet !
Please feel free to close this issue if it is resolved, thank you.

**Comment by changqin26** [comment]
Thanks a lot @lcomet . The issue can be closed now.
