### ISSUE TITLE
ids:UsagePolicyClass NOT subClass of odrl:Policy ?

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/InformationModel#551]
https://github.com/International-Data-Spaces-Association/InformationModel/blob/develop/model/contract/UsagePolicyClass.ttl

**Comment by changqin26** [comment]
Thanks for the hint. ids:UsagePolicyClass should be the subclass of odrl:Policy. We will add it.

**Comment by changqin26** [comment]
Hi @jlangkau, sorry I overlooked something in the Infomodel. In the IDS infomodl, ids:Contract is the subClassOf odrl:Policy. Please see here: https://github.com/International-Data-Spaces-Association/InformationModel/blob/e9bc60fb2c260728cbcd767be744b44c5b665112/model/contract/Contract.ttl#L14

Hi @hosseinzadeha, can you please help me with this point: Is there a relation between ids:Contract and ids:UsagePolicyClass? If yes, what should it be?  Thanks in advance!

**Comment by hosseinzadeha** [comment]
@changqin26 Hi, I bring the three definitions here:
**An IDS Contract** is implicitly divided to two main sections: the contract specific metadata and the IDS Usage Control Policy of the contract. 
So an IDS policy is a part of a Contract which contains usage restrictions.
**A Usage Policy Class** is an atomic policy template that refers to a specific restriction on the data usage. For example, "restricting the usage to a time interval", or "restricting the usage to a specific location".
Eventually, **a Usage Control policy** is a combination of one or more instances of the policy classes that is identified and is referring to a specific piece of data. For example: "The Data Consumer X shall use my data not later than 31st of March 2022 and only when the location is Germany."
In my opinion, right now, an IDS Usage Policy Class could not be a subClass of odrl:policy because we have extended the ODRL policy language and we have some elements that are not defined in ODRL.

**Comment by changqin26** [comment]
Many thanks @hosseinzadeha for your explanation!
@jlangkau, I hope @hosseinzadeha's comment also helps you and I will close the issue.
