### ISSUE TITLE
Some Links on the Widoco Page are not Clickable

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#553]
See https://w3id.org/idsa/core, which redirects to https://international-data-spaces-association.github.io/InformationModel/docs/index.html#

![image](https://user-images.githubusercontent.com/15930331/161569768-ee6eefe6-b937-4b3a-9f97-6a90e25fbeb0.png)

Clicking on any class or property (e.g., `AppRoute`) [adds a redirect within the current page](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#/AppRoute), which however does not do anything. The expected behavior would be to jump to that position.

Since [it is working for Gaia-X](https://w3id.org/gaia-x/core), which is using the same Widoco build pipeline, inspecting/comparing both w3id configurations might help: [IDS](https://github.com/perma-id/w3id.org/blob/master/idsa/.htaccess) vs. [Gaia-X](https://github.com/perma-id/w3id.org/blob/master/gaia-x/.htaccess).

**Comment by lcomet** [comment]
The problem was originated from the wrong formatting of the hrefs. 
The solution includes the modification of the script generating the documentation to include the removal of trailing slashes for the .html files referring to the overview section. Moreover, the manual modification of the .html files for older versions of the document.
The following commits close this issue: 017d8d9f750bc658ec3d33628a5424dd31882008 and 93f542a47698afcd32aad44dee74de26d3961500
