### ISSUE TITLE
Support for defining custom policy constraint predicates (i.e. leftOperand)

### ISSUE THREAD

**Issue by jpullmann** [International-Data-Spaces-Association/InformationModel#62]
Currently the predicates used in policy constraints (`leftOperand`) are defined informally by the ODRL CG, for example [odrl:language](https://www.w3.org/TR/odrl-vocab/#term-language). The predicate semantics, requirements on interpretation (e.g. which internal context model is needed to decide upon), compatible operators and eligible value range (i.e. types of values in `rightOperand`) should be defined in an unambiguous and possibly formal, machine-interpretable manner.

**Comment by sebbader** [comment]
Necessary form of each IDS LeftOperand:
- MUST: Textual description
- SHOULD: a formal definition and/or relations to other LeftOperands (refinements or skos:broader  statements `:eventHasHappenedInPast skos:broader :eventExists` (Remark: not `skos:broaderTransitive`, see SKOS definition))
- MUST: references to valid Operators (maybe something like `<left operand> :hasOperators ( :operator1 :operator2 :operator3 :operator4 )`, not necessarily in RDF
- SHOULD: The set of allowed RightOperands should be described (see #63 ). 

- Open to discussion: where are the descriptions located? As part of the Information Model or potentially through a IDS VocabularyProvider?
       - Prominent LeftOperands for the templates should be part of the Information Model.

**Comment by sebbader** [comment]
A (new?) predicate is required to reference (remote?) endpoints in order to request the actually realized RightOperand/value.

I can think of several alternative approaches, all with their justified scenarios:
- It's up to the usage control system to find the endpoint. We trust the UC as it is a certified IDS component. No need for further clarifications.
- DAPS provides RightOperands, for instance security levels. No need for further clarifications.
- a custom endpoint E provides RightOperands, both participants trust E as they agreed on its usage during a negotiation phase. In this case, the agreement should contain a reference to E, therefore needing a repsective property.

**Comment by sebbader** [comment]
The updates on the Usage Policy Language and the additional descritpions in the IM itself have solved this issue in the meantime.

**Comment by jlangkau** [comment]
@sebbader : one qustion only - what was ment by that?

> DAPS provides RightOperands, for instance security levels. No need for further clarifications.
